apiVersion: v1
kind: ConfigMap
metadata:
  name: loyalty-batch-engine-config
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_BATCH_JOB_ENABLED: "false"
  LOGGING_LEVEL_COM_LOYALTY: "INFO"
  SERVER_PORT: "9874"